### ISSUE TITLE
Start coding: co-forest

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-recommendation-attack-detection#14]

**Comment by phf1001** [comment]
@alvarag a better pseudocode can be found in page 85 of [Engelen Thesis](https://theses.liacs.nl/pdf/2018-2019-EngelenJEvan.pdf). The code needs to be debugged after the meeting.

**Comment by alvarag** [comment]
Do you want that I review the code?

**Comment by phf1001** [comment]
Ahora respondo en git, pero mi idea era mirarlo juntos mañana. Tengo bastantes dudas sobre los tipos de datos (cuál es mejor) y sobre cómo almacenar algunas cosas. Además tengo que dar un repaso porque la complejidad algorítmica es horrible y se puede optimizar muchísimo, pero prefiero comentarlo contigo mañana. Falta alguna mini cosita por implementar (que los árboles se entrenen con Bootstrap y así).

Te puse el @ más que nada para que supieses que el pseudocódigo que estoy siguiendo es el de Engelen, me parece que tiene bastante más coherencia (mañana te lo comento).

Gracias,
Patricia.
De: Álvar ***@***.***>
Enviado: miércoles, 2 de noviembre de 2022 11:17
Para: ***@***.***>
CC: Patricia Hernando ***@***.***>; State ***@***.***>
Asunto: Re: [phf1001/semisupervised-recommendation-attack-detection] Start coding: co-forest (Issue #14)


Do you want that I review the code?

**Comment by phf1001** [comment]
There is no need, we can discuss it tomorrow.

Thank you.
