### ISSUE TITLE
docs: memoir

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-recommendation-attack-detection#21]

**Comment by alvarag** [comment]
Some minor comments on the documentation

[anexosAAG.pdf](https://github.com/phf1001/semisupervised-recommendation-attack-detection/files/10074708/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/phf1001/semisupervised-recommendation-attack-detection/files/10074709/memoriaAAG.pdf)

**Comment by phf1001** [comment]
@alvarag Experiments have been done with N = 20 instead of N = 6 (as used in the bibliography) because it reports a better performance for the toy datasets. However, they can be repeated once the W issue is solved.
