### ISSUE TITLE
Some comments on the documentation

### ISSUE THREAD

**Issue by alvarag** [phf1001/semisupervised-recommendation-attack-detection#31]
[anexosAAG.pdf](https://github.com/phf1001/semisupervised-recommendation-attack-detection/files/10177773/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/phf1001/semisupervised-recommendation-attack-detection/files/10177774/memoriaAAG.pdf)

**Comment by phf1001** [comment]
@alvarag Everything is corrected except the "time experiments", that have been added to the backlog and will be included soon.
